max_epochs: 50
accelerator: auto
devices: auto
precision: 16-mixed

save_top_k: 3
early_stopping_patience: 5

gradient_clip_val: 1.0
accumulate_grad_batches: 1
log_every_n_steps: 50

deterministic: true
